http in npm-shrinkwrap.json (#169)
* Add pre-commit check for http:// URL in shrinkwrap

See http://blog.npmjs.org/post/154400916805/avoid-http-urls-in-shrinkwrap-files

* HTTP->HTTPS in shrinkwrap

diff --git a/tasks/pre-commit b/tasks/pre-commit
--- a/tasks/pre-commit
+++ b/tasks/pre-commit
@@ -24,6 +24,10 @@ else # Running locally
     git diff-index --check --cached $against
 fi
 
+if grep --quiet http: npm-shrinkwrap.json; then
+  echo "Error: insecure HTTP URL found in npm-shrinkwrap.json"
+  exit 1
+fi
 ruby -c Gemfile >/dev/null
 ruby -c config/environment.rb >/dev/null
 ruby -c tasks/elasticsearch.rake >/dev/null
